# Generated by Django 4.1.1 on 2023-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0002_simpleuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
