# Generated by Django 4.1.1 on 2023-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0003_simpleuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='phn_num',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_imgs/'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/'),
        ),
    ]
