# Generated by Django 4.1.1 on 2023-11-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cms', '0005_alter_article_image_alter_simpleuser_phn_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
